<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Manga', 'doctrine');

/**
 * BaseManga
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $number
 * 
 * @method integer getId()     Returns the current record's "id" value
 * @method string  getName()   Returns the current record's "name" value
 * @method integer getNumber() Returns the current record's "number" value
 * @method Manga   setId()     Sets the current record's "id" value
 * @method Manga   setName()   Sets the current record's "name" value
 * @method Manga   setNumber() Sets the current record's "number" value
 * 
 * @package    mymanga
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseManga extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('manga');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('number', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}