<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MEpisode', 'doctrine');

/**
 * BaseMEpisode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $first_page
 * @property string $path
 * @property integer $season_id
 * @property integer $click_count
 * @property MSeason $MSeason
 * @property Doctrine_Collection $MPicture
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getFirstPage()   Returns the current record's "first_page" value
 * @method string              getPath()        Returns the current record's "path" value
 * @method integer             getSeasonId()    Returns the current record's "season_id" value
 * @method integer             getClickCount()  Returns the current record's "click_count" value
 * @method MSeason             getMSeason()     Returns the current record's "MSeason" value
 * @method Doctrine_Collection getMPicture()    Returns the current record's "MPicture" collection
 * @method MEpisode            setId()          Sets the current record's "id" value
 * @method MEpisode            setName()        Sets the current record's "name" value
 * @method MEpisode            setFirstPage()   Sets the current record's "first_page" value
 * @method MEpisode            setPath()        Sets the current record's "path" value
 * @method MEpisode            setSeasonId()    Sets the current record's "season_id" value
 * @method MEpisode            setClickCount()  Sets the current record's "click_count" value
 * @method MEpisode            setMSeason()     Sets the current record's "MSeason" value
 * @method MEpisode            setMPicture()    Sets the current record's "MPicture" collection
 * 
 * @package    mymanga
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMEpisode extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('m_episode');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('first_page', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('path', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('season_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('click_count', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MSeason', array(
             'local' => 'season_id',
             'foreign' => 'id'));

        $this->hasMany('MPicture', array(
             'local' => 'id',
             'foreign' => 'episode_id'));
    }
}