<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MPicture', 'doctrine');

/**
 * BaseMPicture
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $index
 * @property string $picture_url
 * @property string $page_url
 * @property string $path
 * @property integer $episode_id
 * @property MEpisode $MEpisode
 * 
 * @method integer  getId()          Returns the current record's "id" value
 * @method integer  getIndex()       Returns the current record's "index" value
 * @method string   getPictureUrl()  Returns the current record's "picture_url" value
 * @method string   getPageUrl()     Returns the current record's "page_url" value
 * @method string   getPath()        Returns the current record's "path" value
 * @method integer  getEpisodeId()   Returns the current record's "episode_id" value
 * @method MEpisode getMEpisode()    Returns the current record's "MEpisode" value
 * @method MPicture setId()          Sets the current record's "id" value
 * @method MPicture setIndex()       Sets the current record's "index" value
 * @method MPicture setPictureUrl()  Sets the current record's "picture_url" value
 * @method MPicture setPageUrl()     Sets the current record's "page_url" value
 * @method MPicture setPath()        Sets the current record's "path" value
 * @method MPicture setEpisodeId()   Sets the current record's "episode_id" value
 * @method MPicture setMEpisode()    Sets the current record's "MEpisode" value
 * 
 * @package    mymanga
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMPicture extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('m_picture');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('index', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('picture_url', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('page_url', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('path', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('episode_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MEpisode', array(
             'local' => 'episode_id',
             'foreign' => 'id'));
    }
}