<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/04/02 11:05:04

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=10.162.181.119;dbname=my',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
