<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/03/29 09:45:37

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=10.162.181.60;dbname=my',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
