<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2013/04/01 11:50:01
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinecli' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrineconnectionlistener' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfwebdebugpaneldoctrine' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfformdoctrine' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinecolumn' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'swift_doctrinespool' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinepager' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrinerecord' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrineroute' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineexception' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrinebasetask' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuilddbtask' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinebuildfilterstask' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinebuildformstask' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildmodeltask' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuildschematask' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildsqltask' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinebuildtask' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinecleanmodelfilestask' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrineconfiguredatabasetask' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinecreatemodeltables' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedatadumptask' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinedataloadtask' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinedeletemodelfilestask' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinedqltask' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinedropdbtask' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinegenerateadmintask' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinegeneratemigrationtask' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegeneratemoduletask' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrineinsertsqltask' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinemigratetask' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sftesterdoctrine' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfvalidatordoctrinechoice' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfwidgetformdoctrinechoice' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/vendor/symfony-1.4.19/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',

  // project
  'baseform' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/form/BaseForm.class.php',

  // project_model
  'basemanga' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/model/doctrine/base/BaseManga.class.php',
  'basemepisode' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/model/doctrine/base/BaseMEpisode.class.php',
  'basempicture' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/model/doctrine/base/BaseMPicture.class.php',
  'basemseason' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/model/doctrine/base/BaseMSeason.class.php',
  'basemvolume' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/model/doctrine/base/BaseMVolume.class.php',
  'mepisode' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/model/doctrine/MEpisode.class.php',
  'mepisodetable' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/model/doctrine/MEpisodeTable.class.php',
  'mpicture' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/model/doctrine/MPicture.class.php',
  'mpicturetable' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/model/doctrine/MPictureTable.class.php',
  'mseason' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/model/doctrine/MSeason.class.php',
  'mseasontable' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/model/doctrine/MSeasonTable.class.php',
  'mvolume' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/model/doctrine/MVolume.class.php',
  'mvolumetable' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/lib/model/doctrine/MVolumeTable.class.php',

  // application
  'myuser' => 'C:/Users/kshu.ADOBENET/workspace/manga/mymanga/apps/frontend/lib/myUser.class.php',

  // modules
);
