<?php

/**
 * MangaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MangaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MangaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Manga');
    }
}