<?php

/**
 * MEpisodeTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MEpisodeTable extends Doctrine_Table
{
	/**
	 * Returns an instance of this class.
	 *
	 * @return object MEpisodeTable
	 */
	public static function getInstance()
	{
		return Doctrine_Core::getTable('MEpisode');
	}

	public function getEpisodeListBySeasonId($seasonId){
		$season = Doctrine::getTable("MSeason")->findOneBy("id", $seasonId);
		if(!$season){
			throw new Exception("season id: ".$seasonId." is not exist!");
		}
		$clickCount = $season->getClickCount() + 1;
		$season->setClickCount($clickCount);
		$season->save();
		return Doctrine::getTable("MEpisode")->findBy("season_id", $seasonId);
	}
}