<?php

/**
 * MSeasonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MSeasonTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MSeasonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MSeason');
    }
}