<?php

/**
 * MSeasonTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MSeasonTable extends Doctrine_Table
{
	/**
	 * Returns an instance of this class.
	 *
	 * @return object MSeasonTable
	 */
	public static function getInstance()
	{
		return Doctrine_Core::getTable('MSeason');
	}

	public function getSeasonListByVolumeId($volumeId){
		$volume = Doctrine::getTable("MVolume")->findOneBy("id", $volumeId);
		if(!$volume){
			throw new Exception("volume id: ".$volume." is not exist!");
		}
		$clickCount = $volume->getClickCount() + 1;
		$volume->setClickCount($clickCount);
		$volume->save();
		return Doctrine::getTable("MSeason")->findBy("volume_id", $volumeId);
	}

	public function getHotSeasons(){
		return Doctrine::getTable("MSeason")
		->createQuery("ms")
		->orderBy("ms.click_count DESC")
		->limit(10)
		->offset(0)
		->execute();
	}
}