<?php

/**
 * MVolumeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MVolumeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MVolumeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MVolume');
    }
}